site_name: TheMap Python Documentation
theme: readthedocs
dev_addr: '0.0.0.0:8070'
nav:
    - 'Getting started' : 'index.md'
    - Introdcution : 'introduction.md'
    - 'Map Functions' : 'map.md'
    - 'Layer Functions' : 'layer.md'
    - 'Common Functions' : 'common.md'
    - Concepts : 
        - 'Map Options' : 'concepts/map_options.md'
        - 'Layer Options' : 'concepts/layer_options.md'
        - 'Link Layer Options' : 'concepts/link_layer_options.md'
        - 'Image Layer Options' : 'concepts/image_layer_options.md'
        - 'Layer Style' : 'concepts/layer_style_definition.md'
        - 'Feature Content Template' : 'concepts/feature_content_template.md'
    - Objects : 
        - 'Map' : 'objects/map.md'
        - 'Layer' : 'objects/layer.md'
        - 'Link Layer' : 'objects/link_layer.md'
        - 'Image Layer' : 'objects/image_layer.md'
    - Examples : 
        - 'Data Map' : 'examples/data_map.md'
        - 'Image Map' : 'examples/image_map.md'
        - 'Link Map' : 'examples/link_map.md'
    - 'Web Portal': 'https://themap.io'